# Generated by Django 4.2.4 on 2023-08-26 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('tank', 'Танк'), ('heal', 'Хил'), ('dd', 'ДД'), ('trader', 'Торговец'), ('gild', 'Гилдмастер'), ('quest', 'Квестгивер'), ('blacksmith', 'Кузнец'), ('leatherworker', 'Кожевник'), ('potion', 'Зельевар'), ('spell', 'Мастер заклинаний')], default='tank', max_length=13)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='game/')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='game/')),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to='game/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('dateCreation', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.post')),
            ],
        ),
    ]
